import type { ModuloSistema, ModuloSistemaConfig } from '../types/authorization.types';

export const MODULOS_SISTEMA: readonly ModuloSistemaConfig[] = [
  {
    codigo: 'dashboard',
    nombre: 'Dashboard',
    ruta: '/app/dashboard',
    icono: 'dashboard',
    orden: 1,
    activo: true,
  },
  {
    codigo: 'clientes',
    nombre: 'Clientes',
    ruta: '/app/customers',
    icono: 'people',
    orden: 2,
    activo: true,
  },
  {
    codigo: 'citas',
    nombre: 'Citas',
    ruta: '/app/appointments',
    icono: 'event',
    orden: 3,
    activo: true,
  },
  {
    codigo: 'horario',
    nombre: 'Horario',
    ruta: '/app/schedule',
    icono: 'schedule',
    orden: 4,
    activo: true,
  },
  {
    codigo: 'disponibilidad',
    nombre: 'Disponibilidad',
    ruta: '/app/availability',
    icono: 'event_available',
    orden: 5,
    activo: true,
  },
  {
    codigo: 'servicios',
    nombre: 'Servicios',
    ruta: '/app/services',
    icono: 'design_services',
    orden: 6,
    activo: true,
  },
  {
    codigo: 'empleados',
    nombre: 'Profesionales',
    ruta: '/app/employees',
    icono: 'badge',
    orden: 7,
    activo: true,
  },
  {
    codigo: 'pedidos',
    nombre: 'Pedidos',
    ruta: '/app/orders',
    icono: 'shopping_cart',
    orden: 8,
    activo: true,
  },
  {
    codigo: 'productos',
    nombre: 'Productos',
    ruta: '/app/products',
    icono: 'inventory_2',
    orden: 9,
    activo: true,
  },
  {
    codigo: 'inventario',
    nombre: 'Inventario',
    ruta: '/app/inventory',
    icono: 'warehouse',
    orden: 10,
    activo: true,
  },
  {
    codigo: 'finanzas',
    nombre: 'Finanzas',
    ruta: '/app/finance',
    icono: 'payments',
    orden: 11,
    activo: true,
  },
  {
    codigo: 'conversaciones',
    nombre: 'Conversaciones',
    ruta: '/app/conversations',
    icono: 'chat',
    orden: 12,
    activo: true,
  },
  {
    codigo: 'llamadas',
    nombre: 'Llamadas',
    ruta: '/app/calls',
    icono: 'phone',
    orden: 13,
    activo: true,
  },
  {
    codigo: 'whatsapp',
    nombre: 'WhatsApp',
    ruta: '/app/whatsapp',
    icono: 'chat',
    orden: 14,
    activo: true,
  },
  {
    codigo: 'automatizaciones',
    nombre: 'Automatizaciones',
    ruta: '/app/automations',
    icono: 'auto_awesome',
    orden: 15,
    activo: true,
  },
  {
    codigo: 'recordatorios',
    nombre: 'Recordatorios',
    ruta: '/app/reminders',
    icono: 'notifications',
    orden: 16,
    activo: true,
  },
  {
    codigo: 'ai',
    nombre: 'Agente IA',
    ruta: '/app/ai',
    icono: 'smart_toy',
    orden: 17,
    activo: true,
  },
  {
    codigo: 'integraciones',
    nombre: 'Integraciones',
    ruta: '/app/integrations',
    icono: 'extension',
    orden: 18,
    activo: true,
  },
  {
    codigo: 'reportes',
    nombre: 'Reportes',
    ruta: '/app/reports',
    icono: 'bar_chart',
    orden: 19,
    activo: true,
  },
  {
    codigo: 'usuarios',
    nombre: 'Usuarios',
    ruta: '/app/users',
    icono: 'manage_accounts',
    orden: 20,
    activo: true,
  },
  {
    codigo: 'configuracion',
    nombre: 'Configuración',
    ruta: '/app/settings',
    icono: 'settings',
    orden: 21,
    activo: true,
  },
  {
    codigo: 'suscripcion',
    nombre: 'Suscripción',
    ruta: '/app/subscription',
    icono: 'card_membership',
    orden: 22,
    activo: true,
  },
] as const;

export const ACCIONES_PERMISO = ['ver', 'crear', 'editar', 'eliminar'] as const;

export const MODULOS_SISTEMA_POR_CODIGO: Record<ModuloSistema, ModuloSistemaConfig> =
  MODULOS_SISTEMA.reduce(
    (acc, modulo) => {
      acc[modulo.codigo] = modulo;
      return acc;
    },
    {} as Record<ModuloSistema, ModuloSistemaConfig>,
  );
